name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
  
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign
        
      - name: Generate ipa
        run: |
             mkdir payload
             mv build/ios/iphoneos/Runner.app payload/
             zip -r payload.zip payload
             mv payload.zip ios-app.ipa
       
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: ios-app.ipa
             ls -la
